### ISSUE TITLE
Microsoft.Azure.DocumentDB.Core dep in ReStorage is depreacted

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-tools#39]
### Description

Package should be replaced by Microsoft.Azure.Cosmos and code updated.

### Tasks
- [x] Change package reference
- [x] Fix build errors
- [x] Manual test
- [x] QA

### Acceptance Criterias

- [x] Successfull regression test for cosmos related commands
